/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "triton.h"
#include "accel-pppd/ctrl/ipoe/ipoe.h"
#include "statIPOE.h"

static int handle_statIPOEStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests);
static int handle_statIPOEActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statIPOE(void)
{
    static oid statIPOEStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,6,1 };
    static oid statIPOEActive_oid[] = { 1,3,6,1,4,1,8072,100,1,6,2 };

  /*
   * a debugging statement.  Run the agent with -DstatIPOE to see
   * the output of this debugging statement.
   */
  DEBUGMSGTL(("statIPOE", "Initializing the statIPOE module\n"));

	if (!triton_module_loaded("ipoe"))
		return;

    DEBUGMSGTL(("statIPOE",
                "Initializing statIPOEStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statIPOEStarting", handle_statIPOEStarting,
              statIPOEStarting_oid, OID_LENGTH(statIPOEStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statIPOEStarting" );
    }

    DEBUGMSGTL(("statIPOE",
                "Initializing statIPOEActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statIPOEActive", handle_statIPOEActive,
              statIPOEActive_oid, OID_LENGTH(statIPOEActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statIPOEActive" );
    }


  DEBUGMSGTL(("statIPOE",
              "Done initalizing statIPOE module\n"));
}

static int handle_statIPOEStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = ipoe_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statIPOEStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statIPOEActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = ipoe_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statIPOEActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
