/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "triton.h"
#include "accel-pppd/ctrl/l2tp/l2tp.h"
#include "statL2TP.h"


static int handle_statL2TPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests);
static int handle_statL2TPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statL2TP(void)
{
    static oid statL2TPStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,4,1 };
    static oid statL2TPActive_oid[] = { 1,3,6,1,4,1,8072,100,1,4,2 };

  /*
   * a debugging statement.  Run the agent with -DstatL2TP to see
   * the output of this debugging statement.
   */
  DEBUGMSGTL(("statL2TP", "Initializing the statL2TP module\n"));

	if (!triton_module_loaded("l2tp"))
		return;

    DEBUGMSGTL(("statL2TP",
                "Initializing statL2TPStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statL2TPStarting", handle_statL2TPStarting,
              statL2TPStarting_oid, OID_LENGTH(statL2TPStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statL2TPStarting" );
    }

    DEBUGMSGTL(("statL2TP",
                "Initializing statL2TPActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statL2TPActive", handle_statL2TPActive,
              statL2TPActive_oid, OID_LENGTH(statL2TPActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statL2TPActive" );
    }


  DEBUGMSGTL(("statL2TP",
              "Done initalizing statL2TP module\n"));
}

static int handle_statL2TPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = l2tp_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statL2TPStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statL2TPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = l2tp_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statL2TPActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
