/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "triton.h"
#include "accel-pppd/ctrl/pptp/pptp.h"
#include "statPPTP.h"

static int handle_statPPTPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests);
static int handle_statPPTPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statPPTP(void)
{
    static oid statPPTPStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,3,1 };
    static oid statPPTPActive_oid[] = { 1,3,6,1,4,1,8072,100,1,3,2 };

  /*
   * a debugging statement.  Run the agent with -DstatPPTP to see
   * the output of this debugging statement.
   */
  DEBUGMSGTL(("statPPTP", "Initializing the statPPTP module\n"));

	if (!triton_module_loaded("pptp"))
		return;

    DEBUGMSGTL(("statPPTP",
                "Initializing statPPTPStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPTPStarting", handle_statPPTPStarting,
              statPPTPStarting_oid, OID_LENGTH(statPPTPStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPTPStarting" );
    }

    DEBUGMSGTL(("statPPTP",
                "Initializing statPPTPActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPTPActive", handle_statPPTPActive,
              statPPTPActive_oid, OID_LENGTH(statPPTPActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPTPActive" );
    }


  DEBUGMSGTL(("statPPTP",
              "Done initalizing statPPTP module\n"));
}

static int handle_statPPTPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = pptp_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPTPStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statPPTPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = pptp_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPTPActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
