/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "ap_session.h"
#include "statPPP.h"

static int handle_statPPPStarting(netsnmp_mib_handler *handler,
				  netsnmp_handler_registration *reginfo,
				  netsnmp_agent_request_info *reqinfo,
				  netsnmp_request_info *requests);
static int handle_statPPPActive(netsnmp_mib_handler *handler,
				netsnmp_handler_registration *reginfo,
				netsnmp_agent_request_info *reqinfo,
				netsnmp_request_info *requests);
static int handle_statPPPFinishing(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statPPP(void)
{
    static oid statPPPStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,2,1 };
    static oid statPPPActive_oid[] = { 1,3,6,1,4,1,8072,100,1,2,2 };
    static oid statPPPFinishing_oid[] = { 1,3,6,1,4,1,8072,100,1,2,3 };

  DEBUGMSGTL(("statPPP", "Initializing the statPPP module\n"));

    DEBUGMSGTL(("statPPP",
                "Initializing statPPPStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPPStarting", handle_statPPPStarting,
              statPPPStarting_oid, OID_LENGTH(statPPPStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPPStarting" );
    }

    DEBUGMSGTL(("statPPP",
                "Initializing statPPPActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPPActive", handle_statPPPActive,
              statPPPActive_oid, OID_LENGTH(statPPPActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPPActive" );
    }

    DEBUGMSGTL(("statPPP",
                "Initializing statPPPFinishing scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPPFinishing", handle_statPPPFinishing,
              statPPPFinishing_oid, OID_LENGTH(statPPPFinishing_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPPFinishing" );
    }


  DEBUGMSGTL(("statPPP",
              "Done initalizing statPPP module\n"));
}

static int handle_statPPPStarting(netsnmp_mib_handler *handler,
				  netsnmp_handler_registration *reginfo,
				  netsnmp_agent_request_info *reqinfo,
				  netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = ap_session_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPPStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statPPPActive(netsnmp_mib_handler *handler,
				netsnmp_handler_registration *reginfo,
				netsnmp_agent_request_info *reqinfo,
				netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = ap_session_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPPActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statPPPFinishing(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = ap_session_stat_finishing();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPPFinishing\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
