/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "triton.h"
#include "statPPPOE.h"

unsigned int pppoe_stat_starting(void);
unsigned int pppoe_stat_active(void);

static int handle_statPPPOEStarting(netsnmp_mib_handler *handler,
				    netsnmp_handler_registration *reginfo,
				    netsnmp_agent_request_info *reqinfo,
				    netsnmp_request_info *requests);
static int handle_statPPPOEActive(netsnmp_mib_handler *handler,
				  netsnmp_handler_registration *reginfo,
				  netsnmp_agent_request_info *reqinfo,
				  netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statPPPOE(void)
{
    static oid statPPPOEStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,5,1 };
    static oid statPPPOEActive_oid[] = { 1,3,6,1,4,1,8072,100,1,5,2 };

  /*
   * a debugging statement.  Run the agent with -DstatPPPOE to see
   * the output of this debugging statement.
   */
  DEBUGMSGTL(("statPPPOE", "Initializing the statPPPOE module\n"));

	if (!triton_module_loaded("pppoe"))
		return;

    DEBUGMSGTL(("statPPPOE",
                "Initializing statPPPOEStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPPOEStarting", handle_statPPPOEStarting,
              statPPPOEStarting_oid, OID_LENGTH(statPPPOEStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPPOEStarting" );
    }

    DEBUGMSGTL(("statPPPOE",
                "Initializing statPPPOEActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statPPPOEActive", handle_statPPPOEActive,
              statPPPOEActive_oid, OID_LENGTH(statPPPOEActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statPPPOEActive" );
    }


  DEBUGMSGTL(("statPPPOE",
	              "Done initalizing statPPPOE module\n"));
}

static int handle_statPPPOEStarting(netsnmp_mib_handler *handler,
				    netsnmp_handler_registration *reginfo,
				    netsnmp_agent_request_info *reqinfo,
				    netsnmp_request_info *requests)
{
	long stat;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = pppoe_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPPOEStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statPPPOEActive(netsnmp_mib_handler *handler,
				  netsnmp_handler_registration *reginfo,
				  netsnmp_agent_request_info *reqinfo,
				  netsnmp_request_info *requests)
{
	long stat;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = pppoe_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statPPPOEActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
