/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "triton.h"
#include "accel-pppd/ctrl/sstp/sstp.h"
#include "statSSTP.h"

static int handle_statSSTPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests);
static int handle_statSSTPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests);

/*
 * Our initialization routine, called automatically by the agent
 * (Note that the function name must match init_FILENAME())
 */
void
init_statSSTP(void)
{
    static oid statSSTPStarting_oid[] = { 1,3,6,1,4,1,8072,100,1,7,1 };
    static oid statSSTPActive_oid[] = { 1,3,6,1,4,1,8072,100,1,7,2 };

  /*
   * a debugging statement.  Run the agent with -DstatSSTP to see
   * the output of this debugging statement.
   */
  DEBUGMSGTL(("statSSTP", "Initializing the statSSTP module\n"));

	if (!triton_module_loaded("sstp"))
		return;

    DEBUGMSGTL(("statSSTP",
                "Initializing statSSTPStarting scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statSSTPStarting", handle_statSSTPStarting,
              statSSTPStarting_oid, OID_LENGTH(statSSTPStarting_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statSSTPStarting" );
    }

    DEBUGMSGTL(("statSSTP",
                "Initializing statSSTPActive scalar integer.  Default value = %d\n",
                0));
    if (netsnmp_register_scalar(netsnmp_create_handler_registration(
             "statSSTPActive", handle_statSSTPActive,
              statSSTPActive_oid, OID_LENGTH(statSSTPActive_oid),
              HANDLER_CAN_RONLY)) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register statSSTPActive" );
    }


  DEBUGMSGTL(("statSSTP",
              "Done initalizing statSSTP module\n"));
}

static int handle_statSSTPStarting(netsnmp_mib_handler *handler,
				   netsnmp_handler_registration *reginfo,
				   netsnmp_agent_request_info *reqinfo,
				   netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = sstp_stat_starting();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statSSTPStarting\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}

static int handle_statSSTPActive(netsnmp_mib_handler *handler,
				 netsnmp_handler_registration *reginfo,
				 netsnmp_agent_request_info *reqinfo,
				 netsnmp_request_info *requests)
{
	long stat;

	(void)handler;
	(void)reginfo;

	switch (reqinfo->mode) {
	case MODE_GET:
		stat = sstp_stat_active();
		snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
					 (u_char *)&stat, sizeof(stat));
		break;
	default:
		snmp_log(LOG_ERR, "unknown mode (%d) in handle_statSSTPActive\n", reqinfo->mode);
		return SNMP_ERR_GENERR;
	}

	return SNMP_ERR_NOERROR;
}
